services:
  - type: web
    name: empty-area-config
    runtime: docker
    plan: free
    envVars:
      - key: ROBOT_ID
        sync: false
      - key: CUSTOMER_HOST
        sync: false
      - key: CUSTOMER_URL
        sync: false
      - key: AUTH_CONFIG_PATH
        value: /etc/secrets/auth_config.json
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
